#!/usr/bin/env bun
/**
 * AutoDev Interactive Setup Wizard
 * Guides you through the complete setup process
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { execSync } from "child_process";

const colors = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  red: "\x1b[31m",
  cyan: "\x1b[36m",
};

const c = colors;

function header(text: string) {
  console.log("\n" + "=".repeat(70));
  console.log(c.bright + c.cyan + text + c.reset);
  console.log("=".repeat(70) + "\n");
}

function success(text: string) {
  console.log(c.green + "✅ " + text + c.reset);
}

function warning(text: string) {
  console.log(c.yellow + "⚠️  " + text + c.reset);
}

function error(text: string) {
  console.log(c.red + "❌ " + text + c.reset);
}

function info(text: string) {
  console.log(c.blue + "ℹ️  " + text + c.reset);
}

function prompt(question: string): Promise<string> {
  return new Promise((resolve) => {
    process.stdout.write(c.bright + question + c.reset + " ");
    process.stdin.once("data", (data) => {
      resolve(data.toString().trim());
    });
  });
}

async function main() {
  console.clear();

  header("🚀 AutoDev Setup Wizard");

  console.log("Welcome! This wizard will help you set up AutoDev step-by-step.\n");
  console.log("AutoDev automates small GitHub issues using AI agents.");
  console.log("It creates PRs automatically when you label issues with 'auto-dev'.\n");

  const ready = await prompt("Ready to begin? (y/n)");
  if (ready.toLowerCase() !== "y") {
    console.log("\nNo problem! Run this script again when you're ready.");
    process.exit(0);
  }

  // Step 1: Check Bun
  header("Step 1/6: Checking Bun Installation");
  try {
    const bunVersion = execSync("bun --version", { encoding: "utf-8" }).trim();
    success(`Bun ${bunVersion} is installed`);
  } catch {
    error("Bun is not installed!");
    console.log("\nPlease install Bun first:");
    console.log("  curl -fsSL https://bun.sh/install | bash\n");
    process.exit(1);
  }

  // Step 2: Install dependencies
  header("Step 2/6: Installing Dependencies");
  console.log("Running: bun install\n");
  try {
    execSync("bun install", { stdio: "inherit" });
    success("Dependencies installed");
  } catch {
    error("Failed to install dependencies");
    process.exit(1);
  }

  // Step 3: Environment variables
  header("Step 3/6: Configuring Environment Variables");

  const envPath = ".env.local";
  let envContent = "";

  if (existsSync(envPath)) {
    const overwrite = await prompt(".env.local already exists. Overwrite? (y/n)");
    if (overwrite.toLowerCase() !== "y") {
      warning("Skipping environment setup. Using existing .env.local");
      envContent = readFileSync(envPath, "utf-8");
    }
  }

  if (!envContent) {
    console.log("\nLet's configure your API keys and credentials.\n");

    // GitHub Token
    info("GitHub Personal Access Token");
    console.log("  Get it from: https://github.com/settings/tokens");
    console.log("  Required permissions: repo, workflow\n");
    const githubToken = await prompt("Enter your GitHub token:");

    // Anthropic API Key
    console.log();
    info("Anthropic API Key (for Claude)");
    console.log("  Get it from: https://console.anthropic.com/");
    console.log("  Make sure you have credits available\n");
    const anthropicKey = await prompt("Enter your Anthropic API key:");

    // Database URL
    console.log();
    info("Neon PostgreSQL Database");
    console.log("  Create free database: https://console.neon.tech/");
    console.log("  Copy the connection string (starts with postgresql://)\n");
    const databaseUrl = await prompt("Enter your database URL:");

    // GitHub Repo
    console.log();
    info("GitHub Repository");
    console.log("  Which repo should AutoDev monitor?");
    console.log("  Format: owner/repo (e.g., myusername/my-test-repo)\n");
    const allowedRepos = await prompt("Enter repository:");

    // Linear (optional)
    console.log();
    info("Linear API Key (Optional)");
    console.log("  Press Enter to skip, or get from: https://linear.app/settings/api\n");
    const linearKey = await prompt("Enter Linear API key (or press Enter):");

    // Webhook secret
    console.log();
    info("GitHub Webhook Secret");
    console.log("  This secures your webhook endpoint");
    console.log("  Press Enter to generate random secret\n");
    let webhookSecret = await prompt("Enter webhook secret (or press Enter):");
    if (!webhookSecret) {
      webhookSecret = crypto.randomUUID();
      info(`Generated secret: ${webhookSecret}`);
    }

    // Write .env.local
    envContent = `# AutoDev Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# Server
PORT=3000
NODE_ENV=development

# GitHub
GITHUB_TOKEN=${githubToken}
GITHUB_WEBHOOK_SECRET=${webhookSecret}

# Anthropic (Claude)
ANTHROPIC_API_KEY=${anthropicKey}

# Database (Neon PostgreSQL)
DATABASE_URL=${databaseUrl}

# Linear (optional)
LINEAR_API_KEY=${linearKey}

# Configuration
MAX_ATTEMPTS=3
MAX_DIFF_LINES=300
ALLOWED_REPOS=${allowedRepos}
`;

    writeFileSync(envPath, envContent);
    success("Environment configuration saved to .env.local");
  }

  // Step 4: Database migrations
  header("Step 4/6: Setting Up Database");
  console.log("Running migrations to create tables...\n");
  try {
    execSync("bun run db:migrate", { stdio: "inherit" });
    success("Database tables created");
  } catch {
    error("Failed to run migrations");
    console.log("\nPlease check your DATABASE_URL is correct");
    process.exit(1);
  }

  // Step 5: Test connection
  header("Step 5/6: Testing Setup");
  console.log("Running verification tests...\n");
  try {
    execSync("bun run test-setup.ts", { stdio: "inherit" });
    success("All tests passed!");
  } catch {
    error("Some tests failed");
    console.log("\nPlease check the error messages above");
    process.exit(1);
  }

  // Step 6: Next steps
  header("Step 6/6: You're All Set! 🎉");

  console.log(c.green + c.bright + "AutoDev is ready to use!\n" + c.reset);

  console.log("📋 Quick Start:\n");
  console.log("  1. Start the server:");
  console.log(c.cyan + "     bun run dev" + c.reset);
  console.log();
  console.log("  2. Test with a webhook:");
  console.log(c.cyan + "     bun run test-webhook.ts" + c.reset);
  console.log();
  console.log("  3. Configure GitHub webhook:");
  console.log("     • Go to your repo → Settings → Webhooks");
  console.log("     • Add webhook: http://localhost:3000/webhooks/github");
  console.log("     • Content type: application/json");
  console.log("     • Secret: (use the one from .env.local)");
  console.log("     • Events: Issues, Check runs");
  console.log();
  console.log("  4. Create an issue and add label: " + c.yellow + "auto-dev" + c.reset);
  console.log();
  console.log("📚 Documentation:");
  console.log("  • Quick Start:  cat QUICKSTART.md");
  console.log("  • Full Guide:   cat CLAUDE.md");
  console.log("  • Testing:      cat TESTING.md");
  console.log();
  console.log("🚀 Deploy to production:");
  console.log(c.cyan + "   fly deploy" + c.reset);
  console.log();

  const startNow = await prompt("Start the server now? (y/n)");
  if (startNow.toLowerCase() === "y") {
    console.log("\n" + c.bright + "Starting AutoDev server..." + c.reset + "\n");
    execSync("bun run dev", { stdio: "inherit" });
  } else {
    console.log("\nRun " + c.cyan + "bun run dev" + c.reset + " when you're ready!");
  }
}

main().catch((err) => {
  error("Setup failed: " + err.message);
  process.exit(1);
});
