"""Create PR node for LangGraph."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..state import GraphState


async def create_pr(state: GraphState) -> GraphState:
    """
    Create a pull request based on the current state.

    Args:
        state (GraphState): The current state containing issue information and diff.

    Returns:
        GraphState: Updated state with pr_data and status set to 'pr_ready'.
    """
    issue_number = state.get('issue_number', 'unknown')
    issue_title = state.get('issue_title', 'Unknown Issue')
    diff = state.get('diff', '')

    pr_title = f'fix: {issue_title} (#{issue_number})'
    pr_body = f"""Summary

{issue_title}

Changes

{diff}

Generated by

AutoDev"""
    branch_name = f'autodev/issue-{issue_number}'
    base_branch = 'main'

    pr_data = {
        'title': pr_title,
        'body': pr_body,
        'branch_name': branch_name,
        'base_branch': base_branch,
    }

    new_state = state.copy()
    new_state['pr_data'] = pr_data
    new_state['status'] = 'pr_ready'
    return new_state