"""Node to prepare PR creation data."""
from typing import TYPE_CHECKING, Any, Dict

if TYPE_CHECKING:
    from typing import TypedDict

    class GraphState(TypedDict, total=False):
        issue_number: int
        issue_title: str
        diff: str
        pr_data: Dict[str, str]
        status: str


async def create_pr(state: "GraphState") -> "GraphState":
    """Prepare data for creating a pull request.

    Generates PR title, body, and branch name based on
    the issue and implementation.

    Args:
        state: Current graph state with issue details and diff

    Returns:
        Updated state with pr_data dict containing:
        - title: str
        - body: str
        - branch_name: str
        - base_branch: str
    """
    issue_number = state.get("issue_number", 0)
    issue_title = state.get("issue_title", "Unknown issue")
    diff = state.get("diff", "No diff generated")

    pr_data = {
        "title": f"fix: {issue_title} (#{issue_number})",
        "body": f"""## Summary
Automated implementation for issue #{issue_number}.

## Changes
{diff}

## Generated by
MultiplAI LangGraph Service
""",
        "branch_name": f"autodev/issue-{issue_number}",
        "base_branch": "main",
    }

    return {
        **state,
        "pr_data": pr_data,
        "status": "pr_ready",
    }
